"""Fetch only public scope terms. Never access PDFs or proofreading results."""
import json, time, urllib.parse, urllib.request, urllib.error
from pathlib import Path
ROOT=Path(__file__).resolve().parent
def api(**params):
    url='https://www.wikidata.org/w/api.php?'+urllib.parse.urlencode({'format':'json',**params})
    req=urllib.request.Request(url,headers={'User-Agent':'ChemistryProofreaderDictionary/0.1 (public terminology research)'})
    for attempt in range(3):
        try:
            time.sleep(2)
            with urllib.request.urlopen(req,timeout=30) as response: return json.load(response)
        except urllib.error.HTTPError as error:
            if error.code not in (429,503) or attempt==2: raise
            time.sleep(max(10*(attempt+1), min(60,int(error.headers.get('Retry-After','10')))))
seeds=set(' '.join(l for l in (ROOT/'school-scope.txt').read_text(encoding='utf-8').splitlines() if not l.startswith('#')).split())
cache=ROOT/'wikidata-school-terms.json'
saved=json.loads(cache.read_text(encoding='utf-8')) if cache.exists() else {}
output=saved.get('entries',[]);missing=saved.get('unmatched',[])
gaps=json.loads((ROOT/'public-chemistry-validation.json').read_text(encoding='utf-8'))['unverifiedSeeds']
for term in sorted(seeds):
    # A fixed list of gaps is generated by the offline builder. No private data is used.
    if term not in gaps: continue
    if any(e['term']==term for e in output): continue
    if term in missing: continue
    results=api(action='wbsearchentities',search=term,language='ja',uselang='ja',limit=5)['search']
    matches=[r for r in results if r.get('match',{}).get('text')==term and r.get('match',{}).get('language')=='ja']
    if not matches: missing.append(term); continue
    entities=api(action='wbgetentities',ids='|'.join(r['id'] for r in matches),props='labels|aliases|info',languages='ja')['entities']
    for qid,e in entities.items():
        label=e.get('labels',{}).get('ja',{}).get('value','')
        aliases=[a['value'] for a in e.get('aliases',{}).get('ja',[])]
        if term!=label and term not in aliases: continue
        output.append({'term':term,'entityId':qid,'revision':e['lastrevid'],'label':label,'aliases':aliases,
                       'url':'https://www.wikidata.org/wiki/'+qid,'license':'CC0-1.0'})
        break
    else: missing.append(term)
    cache.write_text(json.dumps({'source':'Wikidata','license':'CC0-1.0','entries':output,'unmatched':missing},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
(ROOT/'wikidata-school-terms.json').write_text(json.dumps({'source':'Wikidata','license':'CC0-1.0','entries':output,'unmatched':missing},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'matched':len(output),'unmatched':missing},ensure_ascii=False))
